version: '3.7'

services:
  ojs3:
    #ports:
     # - "4444:8000"
      # - "443:443"
    #environment:
      #b_ADMIN_USER: /run/secrets/admin_user
      #b_ADMIN_PASSWORD: /run/secrets/admin_password
      #b_ADMIN_EMAIL: /run/secrets/admin_email
      #b_MYSQL_USER: /run/secrets/mysql_user
      #b_MYSQL_PASSWORD: /run/secrets/mysql_password
      #b_MYSQL_DB: /run/secrets/mysql_db
      #b_OJS_BRANCH: ojs-stable-3_1_1
    secrets:
      - admin_user
      - admin_password
      - admin_email
      - mysql_user
      - mysql_password
      - mysql_db
    networks:
      - backend
      - frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=PathPrefixStrip:/ojs"
        - "traefik.frontend.passHostHeader=true"
        # https://github.com/containous/traefik/issues/563#issuecomment-421360934
        #- "traefik.frontend.redirect.regex=^(.*)/ojs$$"
        #- "traefik.frontend.redirect.replacement=$$1/ojs/"
        #- "traefik.frontend.rule=PathPrefix:/ojs;ReplacePathRegex: ^/ojs(.*) /$$1"
        # - "traefik.frontend.rule=PathPrefix:/ojs;PathPrefixStripRegex: ^/ojs(.*) /$$1"
        - "traefik.backend=ojs3"
        - "traefik.port=8000"
        - "traefik.docker.network=frontend"
      restart_policy:
        condition: any
        delay: 0s

secrets:
  admin_user:
    file: admin_user.txt
  admin_password:
    file: admin_password.txt
  admin_email:
    file: admin_email.txt
  mysql_user:
    file: mysql_user.txt
  mysql_password:
    file: mysql_password.txt
  mysql_db:
    file: mysql_db.txt

networks:
  backend:
    name: backend
    external: true
  frontend:
    name: frontend
    external: true
