version: '3.7'

services:
  ojs3:
    image: dainst/cilantro-ojs3
    environment:
      ADMIN_USER_FILE: /run/secrets/ojs_admin_user
      ADMIN_PASSWORD_FILE: /run/secrets/ojs_admin_password
      ADMIN_EMAIL_FILE: /run/secrets/ojs_admin_email
      MYSQL_USER_FILE: /run/secrets/ojs_mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/ojs_mysql_password
      MYSQL_DB_FILE: /run/secrets/ojs_mysql_db
      OJS_BRANCH: "ojs-stable-3_1_1"
    secrets:
      - ojs_admin_user
      - ojs_admin_password
      - ojs_admin_email
      - ojs_mysql_user
      - ojs_mysql_password
      - ojs_mysql_db
    networks:
      - web
    ports:
      - "4444:8000"
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:ojs.test.idai.world"
        - "traefik.passHostHeader=true"
        - "traefik.port=8000"
      restart_policy:
        condition: any
        delay: 0s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"
    volumes:
      - mysqlvolume:/var/lib/mysql
      - appvolume:/var/www/html
      - filesvolume:/var/www/ojsfiles

volumes:
  mysqlvolume:
  appvolume:
  filesvolume:

secrets:
  ojs_admin_user:
    external: true
  ojs_admin_password:
    external: true
  ojs_admin_email:
    external: true
  ojs_mysql_user:
    external: true
  ojs_mysql_password:
    external: true
  ojs_mysql_db:
    external: true

networks:
  web:
    name: web
    external: true
