version: '3.7'

services:
  ojs3:
    build: .
    ports:
      - "80:8000"
    environment:
      - ADMIN_USER="admin"
      - ADMIN_PASSWORD="password"
      - ADMIN_EMAIL="dummy@address.local"
      - MYSQL_USER="ojs"
      - MYSQL_PASSWORD="ojs"
      - MYSQL_DB="ojs"
      - OJS_BRANCH="ojs-stable-3_1_1"
