version: '3.7'

x-env: &env
  MYSQL_USER: ojs
  MYSQL_PASSWORD: ojs
  MYSQL_DB: ojs
  OJS_BRANCH: ojs-stable-3_1_1
  ADMIN_USER: admin
  ADMIN_PASSWORD: password
  ADMIN_EMAIL: dummy@address.local

services:
  ojs3:
    build:
      context: .
      args:
        <<: *env
    image: dainst/cilantro-ojs3
    ports:
      - "4444:8000"
    environment:
      <<: *env
    volumes:
      - mysqlvolume:/var/lib/mysql
      - appvolume:/var/www/html
      - filesvolume:/var/www/ojsfiles

volumes:
  mysqlvolume:
  appvolume:
  filesvolume:
