version: '3.7'

services:
  ojs3:
    #ports:
      #- "4444:8000"
      #- "443:443"
    environment:
      ADMIN_USER_FILE: /run/secrets/admin_user
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password
      ADMIN_EMAIL_FILE: /run/secrets/admin_email
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DB_FILE: /run/secrets/mysql_db
      OJS_BRANCH: "ojs-stable-3_1_1"
    secrets:
      - admin_user
      - admin_password
      - admin_email
      - mysql_user
      - mysql_password
      - mysql_db
    networks:
      - backend
      - frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:ojs.test.idai.world"
        #- "traefik.frontend.rule=Host:ojs.localhost"
        - "traefik.passHostHeader=true"
        - "traefik.port=8000"
      restart_policy:
        condition: any
        delay: 0s

secrets:
  admin_user:
    file: admin_user.txt
  admin_password:
    file: admin_password.txt
  admin_email:
    file: admin_email.txt
  mysql_user:
    file: mysql_user.txt
  mysql_password:
    file: mysql_password.txt
  mysql_db:
    file: mysql_db.txt

networks:
  backend:
    name: backend
    external: true
  frontend:
    name: frontend
    external: true
