version: '3.7'

services:
  ojs3:
    environment:
      ADMIN_USER_FILE: /run/secrets/admin_user
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password
      ADMIN_EMAIL_FILE: /run/secrets/admin_email
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DB_FILE: /run/secrets/mysql_db
      OJS_BRANCH: "ojs-stable-3_1_1"
    secrets:
      - admin_user
      - admin_password
      - admin_email
      - mysql_user
      - mysql_password
      - mysql_db
    networks:
      - web
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:ojs.test.idai.world"
        - "traefik.passHostHeader=true"
        - "traefik.port=8000"
      restart_policy:
        condition: any
        delay: 0s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"

secrets:
  admin_user:
    file: secrets/admin_user.txt
  admin_password:
    file: secrets/admin_password.txt
  admin_email:
    file: secrets/admin_email.txt
  mysql_user:
    file: secrets/mysql_user.txt
  mysql_password:
    file: secrets/mysql_password.txt
  mysql_db:
    file: secrets/mysql_db.txt

networks:
  frontend:
    name: web
    external: true
