version: '3.7'

services:
  ojs3:
    build: .
    volumes:
      - mysqlvolume:/var/lib/mysql
      - appvolume:/var/www/html
      - filesvolume:/var/www/ojsfiles
    ports:
      - "4444:80"
    environment:
      b_ADMIN_USER: /run/secrets/admin_user
      b_ADMIN_PASSWORD: /run/secrets/admin_password
      b_ADMIN_EMAIL: /run/secrets/admin_email
      b_MYSQL_USER: /run/secrets/mysql_user
      b_MYSQL_PASSWORD: /run/secrets/mysql_password
      b_MYSQL_DB: /run/secrets/mysql_db
      b_OJS_BRANCH: ojs-stable-3_1_1
    secrets:
      - admin_user
      - admin_password
      - admin_email
      - mysql_user
      - mysql_password
      - mysql_db

volumes:
  mysqlvolume:
  appvolume:
  filesvolume:

secrets:
  admin_user:
    file: admin_user.txt
  admin_password:
    file: admin_password.txt
  admin_email:
    file: admin_email.txt
  mysql_user:
    file: mysql_user.txt
  mysql_password:
    file: mysql_password.txt
  mysql_db:
    file: mysql_db.txt