version: '3.7'

services:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ${OJS_MYSQL_PASSWORD}
      MYSQL_DATABASE: ojs
    ports:
      - "4306:3306"
    volumes:
      - mysqlvolume:/var/lib/mysql
      - ./mariadb_data/ojs3_dev.sql:/docker-entrypoint-initdb.d/ojs3_dev.sql

  ojs3:
    build:
      context: .
      args:
        OJS_BRANCH: ojs-3_1_2-4
        MYSQL_PASSWORD: ${OJS_MYSQL_PASSWORD}
    image: dainst/ojs3
    ports:
      - "4445:80"
    environment:
      MYSQL_HOST: db
    volumes:
      - ./ojs-cilantro-plugin:/var/www/html/plugins/generic/ojs-cilantro-plugin
      - ./ojs-zenon-plugin:/var/www/html/plugins/pubIds/zenon
      - ./epicur:/var/www/html/plugins/oaiMetadataFormats/epicur
      - ./ojs3_theme:/var/www/html/plugins/themes/idaitheme

volumes:
  mysqlvolume:
