version: '3.7'

services:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ${OJS_MYSQL_PASSWORD}
      MYSQL_DATABASE: ojs
    ports:
      - "4306:3306"
    volumes:
      - mysqlvolume:/var/lib/mysql
      - ./mariadb_data/ojs3_dev.sql:/docker-entrypoint-initdb.d/ojs3_dev.sql
    networks:
      - ojs_dev_network

  ojs:
    container_name: ojs_dev
    build:
      context: .
      args:
        MYSQL_PASSWORD: ${OJS_MYSQL_PASSWORD}
    ports:
      - "4445:80"
    environment:
      MYSQL_HOST: db
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    volumes:
      - ./ojs:/var/www/html
    networks:
      - ojs_dev_network

volumes:
  mysqlvolume:

networks:
  ojs_dev_network:
    name: ojs_dev_network
