version: '3.7'

services:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ojs
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ojs
      MYSQL_DATABASE: ojs
    volumes:
      - mysqlvolume:/var/lib/mysql

  ojs3:
    build:
      context: .
      args:
        OJS_BRANCH: stable-3_1_2
    image: dainst/ojs3
    ports:
      - "4445:80"
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: password
      ADMIN_EMAIL: dummy@address.local
      MYSQL_HOST: db
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ojs
      MYSQL_DATABASE: ojs
    volumes:
      - appvolume:/var/www/html
      - filesvolume:/var/www/ojsfiles

volumes:
  mysqlvolume:
  appvolume:
  filesvolume:
