version: '3.7'

services:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ${OJS_MYSQL_PASSWORD}
      MYSQL_DATABASE: ojs
    volumes:
      - mysqlvolume:/var/lib/mysql
      - .mariadb_data/ojs_3.1.2.4_mysql.sql:/docker-entrypoint-initdb.d/dump.sql

  ojs3:
    build:
      context: .
      args:
        OJS_BRANCH: stable-3_1_2
    image: dainst/ojs3
    ports:
      - "4445:80"
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: ${OJS_ADMIN_PASSWORD}
      ADMIN_EMAIL: dummy@address.local
      MYSQL_HOST: db
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ${OJS_MYSQL_PASSWORD}
      MYSQL_DATABASE: ojs
    volumes:
      - ./ojs-cilantro-plugin:/var/www/html/plugins/generic/ojs-cilantro-plugin
      - ./ojs-zenon-plugin:/var/www/html/plugins/pubIds/zenon
      - ./epicur:/var/www/html/plugins/oaiMetadataFormats/epicur
      - ./ojs-dainst-theme:/var/www/html/plugins/themes/ojs-dainst-theme

volumes:
  mysqlvolume:
